{
 "title": "JWT Pizza Service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pizza Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "latency_pizza_creation_milliseconds_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "latency_service_endpoint_milliseconds_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pizza_revenue_USD_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "rate(pizzas_sold_total[1m])", "legendFormat": "__auto" },
    { "expr": "rate(pizza_failures_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "active_users_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    { "expr": "rate(auth_success_total[1m])", "legendFormat": "__auto" },
    { "expr": "rate(auth_failure_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "__auto" },
    {
     "expr": "rate(http_delete_requests_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_get_requests_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_post_requests_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_put_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}